language: node_js
node_js:
  - "8"

script: yarn run build

cache: yarn

deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $TEM_TICKETS_GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
